#!/bin/bash -l
#SBATCH -p debug 		# change this option for non-debug runs
#SBATCH -t 00:10:00		# adjust the amount of time as necessary
#SBATCH -o serial.%j.stdout
#SBATCH -e serial.%j.error
#SBATCH -N 1			# you'll never need more than 1 node 

srun -n 1 -c 24 ./pthreads -p 24 -n 500 -o pthreads.txt
