#!/bin/bash -l
#SBATCH -t 00:05:00				# adjust the amount of time as necessary
#SBATCH -o auto-mpi24.%j.stdout
#SBATCH -e auto-mpi24.%j.error


NAME=$1
rm $NAME

echo "dims	No.proc	Avg. Rt / Dev.	Eff.	Speedup" >> $NAME
for n in 25 125 1000; do
    srun -n 1 --cpu-freq 2400000 ./dnsmat 1 $n >> $NAME
done


for p in 8 27 125 343 1000; do
  for n in 25 125 1000 10000; do
    srun -n $p --cpu-freq 2400000 ./dnsmat $p $n >> $NAME
  done
done


