#!/bin/bash -l
#SBATCH -t 00:05:00				# adjust the amount of time as necessary
#SBATCH -o auto-mpi24.%j.stdout
#SBATCH -e auto-mpi24.%j.error


NAME=results.txt
rm $NAME

for n in 25 100 1000 10000; do
    srun -n 1 ./dnsmat 1 $n >> $NAME
done


for p in 27 125 343 1000; do
  for n in 25 100 1000 10000; do
    srun -n $p ./dnsmat $p $n >> $NAME
  done
done


