#!/bin/bash

rm serial.out
./serial -n 500 -no -s serial.out
./serial -n 1000 -no -s serial.out
./serial -n 2000 -no -s serial.out
./serial -n 5000 -no -s serial.out
./serial -n 10000 -no -s serial.out
# now run the autograder
./autograder -v serial -s serial.out
